# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Functionalities

on:
  push:
    branches: [ main ]
    paths:
      - '*.py'
      - 'requirements.txt'
      - '*.yml'
      - '*.html'
      - '*.css'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '**/*.yml'
      - '**/*.html'
      - '**/*.css'

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
  
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
          
    - name: Test functionalities
      run: |
        python3 ./oxlet_cli.py -w "sustainable" -o ./outfile.txt
        echo sustainable > infile.txt
        python3 ./oxlet_cli.py -f ./infile.txt -o ./outfile.txt
        
    - name: Test errors
      run: |
        python3 ./oxlet_cli.py -w "; ls -la" -o ./outfile.txt
        python3 ./oxlet_cli.py -w "null" -o ./outfile.txt
        
  

